[package]
name = "write_xyz_traj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libscripts = { path = "../libscripts" }
rayon = "1.5.3"
